name: run bibliographer-github.py

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' #install the python version needed    
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: get bibtex
        run:
          python bibliographer-github.py
      - name: convert bibtex to CSL JSON
        uses: docker://pandoc/core:3.2
        with:
          args: >-  # allows you to break string into multiple lines
            -f
            bibtex
            output.bib
            -t
            csljson
            -o
            middle.json
      - name: convert bibtex to json and add some extras
        run:
          python bibliographer-github-2.py 
      - name: get output in the repo
        uses: stefanzweifel/git-auto-commit-action@v4